default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: localhost

development:
  <<: *default
  database: task_notify_development

test:
  <<: *default
  database: task_notify_test

production:
  <<: *default
  database: task_notify_production
  username: root
  password: 