default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: task_notify_development

test:
  <<: *default
  database: task_notify_test

production:
  <<: *default
  reconnect: false
  database: task_notify_production
  username: task_notify
  password: ziziiyouti
  host: task-notify-mysql.cjaf0vjqgxuf.ap-northeast-1.rds.amazonaws.com