default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  host: localhost

development:
  <<: *default
  database: task_notify_development

test:
  <<: *default
  database: task_notify_test

production:
  <<: *default
  database: task_notify_production
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']