default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ryota
  password: ziziiyouti
  host: localhost

development:
  <<: *default
  database: task_notify_development

test:
  <<: *default
  database: task_notify_test

production:
  <<: *default
  database: task_notify_production
  username: task_notify
  password: <%= ENV['TASK_NOTIFY_DATABASE_PASSWORD'] %>
